### PR TITLE
Add polling options

### PR DESCRIPTION
**Pull request by sbuys**
Add polling options from chokidar. Resolves issues with piping over network and things like virtual machine shared directories.

From paulmillr/chokidar:

"usePolling (default: false). Whether to use fs.watchFile (backed by polling), or fs.watch. If polling leads to high CPU utilization, consider setting this to false. It is typically necessary to set this to true to successfully watch files over a network, and it may be necessary to successfully watch files in other non-standard situations. Setting to true explicitly on OS X overrides the useFsEvents default."

### CODE REVIEW

**Comment by steida** [comment]
For how long you tested that code?

**Comment by sbuys** [comment]
A few days. Been using with chokidar for a while.

**Comment by steida** [comment]
Are you using last version or piping? I had some problem with multiple logging on one file change.

**Comment by sbuys** [comment]
Yes latest version. I'm not seeing that problem on my machines. Did you try changing the interval?

**Pull request merged**
