### PR TITLE
Add option to respawn on exit

### PR DESCRIPTION
**Pull request by mntnoe**
This PR adds the option respawnOnExit, defaulting to true, which is the current behavior. Setting the option to false will only respawn the application after a file change.

The PR also includes some other fixes:
- On some systems, when not using polling, only a single change event is emitted per file. The linked issue has a workaround which has been implemented here for now.
- `worker.kill()` (previously `worker.destroy()`) does not fire SIGTERM event handlers for some reason. Use the old school way of sending this event. This is necessary to get for instance `hapi` to shut down correctly.
- After allowing respawning only on file change, the approach of storing a reference to the current worker became prone to race conditions. Instead, loop over all workers (which should still be one), to prevent multiple running copies.

Feel free to edit or cherry-pick to your likings.

### CODE REVIEW

**Comment by steida** [comment]
Awesome.

**Comment by steida** [comment]
Unfortunately I have no time to test it, it's save for merge?

**Comment by mntnoe** [comment]
Well there are some change to the control flow, so there are always a risk of new bugs, but it's supposed to work as before by default. I'm using the fork with these commits on my project at the moment. I will write if I find any bugs during the next few days.

**Comment by steida** [comment]
Thank you!

**Comment by mntnoe** [comment]
I can test it on Windows during this week, but I do not have access to OSX. Currently on Ubuntu 14.04.

I discovered one regression I forgot about: Error suppression for identical stack traces is no longer in action. I will update the PR with a fix for this one of the following days.

**Comment by steida** [comment]
Thank you. Please remember to push a new functionality behind special option entirely.

**Comment by mntnoe** [comment]
I have now tested the default behavior of upstream version and the forked version on linux (iojs-2.5.0) as well as on windows (node-4.0.0); the behavior being identical.

Setting the respawnOnExit option to false also works as expected on both linux and windows.

**Comment by steida** [comment]
Awesome. I will merge it asap (in a few days). Thanks!

**Comment by mdlawson** [comment]
Merged into `0.3.0`, also bumped chokidar which bumped fsevents, which may effect OSX. @steida can you test?

**Comment by steida** [comment]
Unfortunately we switched to nodemon, so I can't.

**Pull request merged**
